version: '3'
services:

  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env


  backend:
    build: ./backend/src/spliceai
    restart: unless-stopped
    volumes:
      - ./backend/src/spliceai:/src
    #environment:
      # Для отладки (при запуске в релиз убрать!)
      #- FLASK_DEBUG=True
      # Позволяет отслеживать процесс работы приложения в командной строке
      #- PYTHONUNBUFFERED=True
    env_file:
      - .env


  node:
    image: node:14.18.0-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app