version: '3'
services:

  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env

  #GENA
  gena-spliceai:
    build: ./backend/src/gena-spliceai
    restart: unless-stopped
    volumes:
      - ./backend/src/gena-spliceai:/src
    env_file:
      - .env

  gena-deepsea:
    build: ./backend/src/gena-deepsea
    restart: unless-stopped
    volumes:
      - ./backend/src/gena-deepsea:/src
    env_file:
      - .env

  gena-promoters-2000:
    build: ./backend/src/gena-promoters_2000
    restart: unless-stopped
    volumes:
      - ./backend/src/gena-promoters_2000:/src
    env_file:
      - .env

  gena-deepstarr:
    build: ./backend/src/gena-deepstarr
    restart: unless-stopped
    volumes:
      - ./backend/src/gena-deepstarr:/src
    env_file:
      - .env

  #DNABERT
  dnabert-deepstarr:
    build: ./backend/src/DNABERT-DeepSTARR
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-DeepSTARR:/src
      - ./backend/src/DNABERT-DeepSTARR/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env

  dnabert-deepsea:
    build: ./backend/src/DNABERT-DeepSea
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-DeepSea:/src
      - ./backend/src/DNABERT-DeepSea/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env

  dnabert-promoters-2000:
    build: ./backend/src/DNABERT-Promoters_2000
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-Promoters_2000:/src
      - ./backend/src/DNABERT-Promoters_2000/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env

  dnabert-spliceai:
    build: ./backend/src/DNABERT-SpliceAI
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-SpliceAI:/src
      - ./backend/src/DNABERT-SpliceAI/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env

  dnabert-promoters-original:
    build: ./backend/src/DNABERT-Promoters_original
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-Promoters_original:/src
      - ./backend/src/DNABERT-Promoters_original/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env


  node:
    build:
      context: ./docker/node
    volumes:
      - ./frontend:/app
    working_dir: /app