version: '3'
services:

  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env


  gena:
    build: ./backend/src/spliceai
    restart: unless-stopped
    volumes:
      - ./backend/src/spliceai:/src
    #environment:
      # Для отладки (при запуске в релиз убрать!)
      #- FLASK_DEBUG=True
      # Позволяет отслеживать процесс работы приложения в командной строке
      #- PYTHONUNBUFFERED=True
    env_file:
      - .env

  dnabert:
    build: ./backend/src/DeepSTARR
    restart: unless-stopped
    volumes:
      - ./backend/src/DeepSTARR:/src
      - ./backend/src/DeepSTARR/respond/DNABERT_storage:/DNABERT_storage
    #environment:
      # Для отладки (при запуске в релиз убрать!)
      #- FLASK_DEBUG=True
      # Позволяет отслеживать процесс работы приложения в командной строке
      #- PYTHONUNBUFFERED=True
    env_file:
      - .env


  node:
    build:
      context: ./docker/node
    volumes:
      - ./frontend:/app
    working_dir: /app