version: '3'
services:

  nginx:
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    env_file:
      - .env

  #GENA
  gena-spliceai:
    build: ./backend/src/spliceai
    restart: unless-stopped
    volumes:
      - ./backend/src/spliceai:/src
    env_file:
      - .env

  gena-deepsea:
    build: ./backend/src/deepsea
    restart: unless-stopped
    volumes:
      - ./backend/src/deepsea:/src
      - ./backend/src/deepsea/respond/FIX:/
    env_file:
      - .env

  #DNABERT
  dnabert-deepstarr:
    build: ./backend/src/DNABERT-DeepSTARR
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-DeepSTARR:/src
      - ./backend/src/DNABERT-DeepSTARR/respond/DNABERT_storage:/DNABERT_storage
    env_file:
      - .env

  dnabert-deepsea:
    build: ./backend/src/DNABERT-DeepSea
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-DeepSea:/src
      - ./backend/src/DNABERT-DeepSea/respond/FIX:/
    env_file:
      - .env

  dnabert-promoters-2000:
    build: ./backend/src/DNABERT-Promoters_2000
    restart: unless-stopped
    volumes:
      - ./backend/src/DNABERT-Promoters_2000:/src
      - ./backend/src/DNABERT-Promoters_2000/respond/FIX:/
    env_file:
      - .env


  node:
    build:
      context: ./docker/node
    volumes:
      - ./frontend:/app
    working_dir: /app